#!/usr/bin/env python3
"""Distill the lambda compiler into Pythia-160M.

Fine-tune a small causal LM on (sentence → lambda) pairs generated by
Qwen3-4B teacher with GBNF grammar-constrained decoding.

Training format (base-model style, no chat template):
  The dog runs. → λx. runs(dog)<eos>
  Every student reads a book. → ∀x. student(x) → ∃y. book(y) ∧ reads(x, y)<eos>

The model learns to continue "sentence →" with lambda output + EOS.
Loss computed only on the lambda tokens + EOS (not the input sentence).

v2 changes from session 003:
  - EOS token appended to training targets (fixes repetition loops)
  - Structural eval metrics beyond P(λ) (predicate accuracy, parse success, etc.)
  - Grammar validation of student output
  - Novel predicate test (holdout vocab generalization)

Usage:
    uv run python scripts/run_distillation.py

Outputs to results/distillation/
"""

from __future__ import annotations

import json
import sys
import time
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

import torch
from torch.utils.data import DataLoader, Dataset

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tests"))

import structlog

structlog.configure(
    processors=[structlog.dev.ConsoleRenderer()],
    wrapper_class=structlog.make_filtering_bound_logger(20),
)

log = structlog.get_logger()

RESULTS_DIR = Path("results/distillation")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR = Path("models/distilled-compiler")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

STUDENT_MODEL = "EleutherAI/pythia-160m-deduped"


def banner(text: str) -> None:
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def save_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"  Saved: {path}")


# ──────────────────────────── Dataset ─────────────────────────────────


class CompileDataset(Dataset):
    """Dataset of (sentence → lambda) pairs for causal LM training.

    Key change from v1: EOS token is appended to each training target.
    This teaches the student to STOP after producing the lambda expression,
    eliminating the repetition loops observed in session 003.
    """

    def __init__(self, jsonl_path, tokenizer, max_length=256):
        self.examples = []
        self.tokenizer = tokenizer
        self.max_length = max_length

        with open(jsonl_path) as f:
            for line in f:
                r = json.loads(line)
                if r["output"]:
                    self.examples.append(r)

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        r = self.examples[idx]
        eos = self.tokenizer.eos_token or ""

        # Format: "sentence → lambda_output<eos>"
        # EOS is explicitly part of the text so the model learns to emit it.
        text = f"{r['input']} → {r['output']}{eos}"

        encoding = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt",
        )

        input_ids = encoding["input_ids"].squeeze(0)
        attention_mask = encoding["attention_mask"].squeeze(0)

        # Find where "→" starts — loss only on lambda output + EOS
        arrow_text = f"{r['input']} →"
        arrow_enc = self.tokenizer(
            arrow_text,
            truncation=True,
            max_length=self.max_length,
        )
        arrow_len = len(arrow_enc["input_ids"])

        # Labels: -100 for input tokens, real ids for output tokens + EOS
        labels = input_ids.clone()
        labels[:arrow_len] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


def collate_fn(batch):
    """Pad batch to max length."""
    max_len = max(b["input_ids"].size(0) for b in batch)

    input_ids = []
    attention_mask = []
    labels = []

    for b in batch:
        pad_len = max_len - b["input_ids"].size(0)
        input_ids.append(
            torch.cat([
                b["input_ids"],
                torch.zeros(pad_len, dtype=torch.long),
            ])
        )
        attention_mask.append(
            torch.cat([
                b["attention_mask"],
                torch.zeros(pad_len, dtype=torch.long),
            ])
        )
        labels.append(
            torch.cat([
                b["labels"],
                torch.full((pad_len,), -100, dtype=torch.long),
            ])
        )

    return {
        "input_ids": torch.stack(input_ids),
        "attention_mask": torch.stack(attention_mask),
        "labels": torch.stack(labels),
    }


# ──────────────────────────── Training ────────────────────────────────


def train_student(model, tokenizer, train_path, device, *, n_epochs=10):
    """Fine-tune the student on compilation data."""

    banner("TRAINING")

    dataset = CompileDataset(train_path, tokenizer)
    print(f"  Training examples: {len(dataset)}")
    print(f"  EOS token: {tokenizer.eos_token!r} (id={tokenizer.eos_token_id})")

    # Verify EOS is in training targets
    sample = dataset[0]
    has_eos = (sample["labels"] == tokenizer.eos_token_id).any().item()
    print(f"  EOS in labels: {has_eos}")

    loader = DataLoader(
        dataset,
        batch_size=4,
        shuffle=True,
        collate_fn=collate_fn,
    )

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=5e-5, weight_decay=0.01
    )

    total_steps = n_epochs * len(loader)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, total_steps
    )

    model.train()
    epoch_losses = []

    for epoch in range(n_epochs):
        total_loss = 0.0
        n_batches = 0

        for batch in loader:
            batch = {
                k: v.to(device) for k, v in batch.items()
            }

            outputs = model(**batch)
            loss = outputs.loss

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()

            total_loss += loss.item()
            n_batches += 1

        avg_loss = total_loss / n_batches
        epoch_losses.append(avg_loss)
        print(f"  Epoch {epoch + 1}/{n_epochs}: "
              f"loss={avg_loss:.4f}  "
              f"lr={scheduler.get_last_lr()[0]:.2e}")

    return epoch_losses


# ──────────────────────────── Structural Evaluation ───────────────────


def structural_eval(generated: str, expected: str, category: str) -> dict:
    """Evaluate structural quality of a generated lambda expression.

    Returns a dict of metrics beyond simple P(λ).
    """
    from test_montague_grammar import validate as validate_montague

    metrics = {}

    # 1. Grammar parse success
    ok, msg = validate_montague(generated)
    metrics["parses"] = ok

    # 2. Extract predicates from both
    def extract_predicates(text):
        """Extract predicate names (identifiers before parens)."""
        import re
        return set(re.findall(r'([a-z_]{2,})\s*\(', text))

    gen_preds = extract_predicates(generated)
    exp_preds = extract_predicates(expected)

    if exp_preds:
        metrics["pred_precision"] = len(gen_preds & exp_preds) / len(gen_preds) if gen_preds else 0.0
        metrics["pred_recall"] = len(gen_preds & exp_preds) / len(exp_preds)
    else:
        metrics["pred_precision"] = 1.0 if not gen_preds else 0.0
        metrics["pred_recall"] = 1.0

    # 3. Extract variables used
    def extract_vars(text):
        import re
        return set(re.findall(r'(?<![a-z_])([u-z])(?![a-z_])', text))

    gen_vars = extract_vars(generated)
    exp_vars = extract_vars(expected)
    metrics["var_match"] = gen_vars == exp_vars

    # 4. Quantifier presence
    def has_quantifiers(text):
        return {
            "lambda": "λ" in text,
            "forall": "∀" in text,
            "exists": "∃" in text,
            "iota": "ι" in text,
        }

    gen_q = has_quantifiers(generated)
    exp_q = has_quantifiers(expected)
    metrics["quantifier_match"] = gen_q == exp_q

    # 5. Connective presence
    def has_connectives(text):
        return {
            "and": "∧" in text,
            "or": "∨" in text,
            "implies": "→" in text,
            "not": "¬" in text,
        }

    gen_c = has_connectives(generated)
    exp_c = has_connectives(expected)
    metrics["connective_match"] = gen_c == exp_c

    # 6. Repetition detection (the session-003 bug)
    def has_repetition(text, threshold=3):
        """Detect if any token pattern repeats excessively."""
        tokens = text.split()
        if len(tokens) < threshold * 2:
            return False
        for i in range(len(tokens)):
            for length in range(1, 4):
                pattern = tokens[i:i+length]
                if not pattern:
                    continue
                count = 0
                j = i
                while j + length <= len(tokens):
                    if tokens[j:j+length] == pattern:
                        count += 1
                        j += length
                    else:
                        break
                if count >= threshold:
                    return True
        return False

    metrics["has_repetition"] = has_repetition(generated)

    # 7. Length ratio (generated vs expected)
    metrics["length_ratio"] = len(generated) / max(len(expected), 1)

    # 8. Exact match
    metrics["exact_match"] = generated.strip() == expected.strip()

    return metrics


def evaluate_student(model, tokenizer, eval_path, device, *, label=""):
    """Generate lambda for each eval sentence and check quality."""
    from verbum.instrument import LAMBDA_INDICATORS

    if label:
        banner(f"EVALUATION — {label}")
    else:
        banner("EVALUATION")

    model.eval()
    results = []

    with open(eval_path) as f:
        eval_data = [json.loads(line) for line in f]

    for r in eval_data:
        prompt = f"{r['input']} →"
        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        n_prompt = inputs["input_ids"].shape[1]

        with torch.no_grad():
            output = model.generate(
                **inputs,
                max_new_tokens=100,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens = output[0, n_prompt:]
        gen = tokenizer.decode(new_tokens, skip_special_tokens=True)
        gen_line = gen.strip().split("\n")[0].strip()

        has_lambda = "λ" in gen_line or sum(
            gen_line.count(s) for s in LAMBDA_INDICATORS
        ) >= 3

        # Structural eval
        metrics = structural_eval(gen_line, r["output"], r["category"])

        results.append({
            "input": r["input"],
            "expected": r["output"],
            "generated": gen_line,
            "has_lambda": has_lambda,
            "category": r["category"],
            "metrics": metrics,
        })

        parse_sym = "P" if metrics["parses"] else "·"
        rep_sym = "R" if metrics["has_repetition"] else "·"
        pred_sym = f"{metrics['pred_recall']:.0%}" if r["output"] else "—"
        status = "Y" if has_lambda else "X"
        print(f"  {status}{parse_sym}{rep_sym} [{r['category']:15s}] "
              f"pred={pred_sym:>4s}  "
              f"{r['input'][:28]:28s} → {gen_line[:50]}")

    # Aggregate metrics
    n = len(results)
    n_lambda = sum(1 for r in results if r["has_lambda"])
    n_parse = sum(1 for r in results if r["metrics"]["parses"])
    n_rep = sum(1 for r in results if r["metrics"]["has_repetition"])
    n_exact = sum(1 for r in results if r["metrics"]["exact_match"])
    n_quant = sum(1 for r in results if r["metrics"]["quantifier_match"])
    n_conn = sum(1 for r in results if r["metrics"]["connective_match"])

    avg_pred_recall = sum(
        r["metrics"]["pred_recall"] for r in results
    ) / max(n, 1)

    print(f"\n  ── Aggregate Metrics ({n} examples) ──")
    print(f"  P(lambda):          {n_lambda}/{n} ({n_lambda/n:.0%})")
    print(f"  Grammar parse:      {n_parse}/{n} ({n_parse/n:.0%})")
    print(f"  Repetition:         {n_rep}/{n} ({n_rep/n:.0%})")
    print(f"  Exact match:        {n_exact}/{n} ({n_exact/n:.0%})")
    print(f"  Pred recall (avg):  {avg_pred_recall:.0%}")
    print(f"  Quantifier match:   {n_quant}/{n} ({n_quant/n:.0%})")
    print(f"  Connective match:   {n_conn}/{n} ({n_conn/n:.0%})")

    # Per-category breakdown
    cat_metrics = {}
    for r in results:
        cat = r["category"]
        if cat not in cat_metrics:
            cat_metrics[cat] = {"n": 0, "lambda": 0, "parse": 0, "exact": 0, "pred_recall": 0}
        cat_metrics[cat]["n"] += 1
        cat_metrics[cat]["lambda"] += int(r["has_lambda"])
        cat_metrics[cat]["parse"] += int(r["metrics"]["parses"])
        cat_metrics[cat]["exact"] += int(r["metrics"]["exact_match"])
        cat_metrics[cat]["pred_recall"] += r["metrics"]["pred_recall"]

    print(f"\n  ── Per-Category ──")
    for cat in sorted(cat_metrics):
        m = cat_metrics[cat]
        print(f"  {cat:20s}: P(λ)={m['lambda']}/{m['n']}  "
              f"parse={m['parse']}/{m['n']}  "
              f"exact={m['exact']}/{m['n']}  "
              f"pred_recall={m['pred_recall']/m['n']:.0%}")

    rate = n_lambda / n if n else 0
    return results, rate


# ──────────────────────────── Main ────────────────────────────────────


def main():
    start = time.time()
    banner(f"DISTILLATION v2 — {datetime.now(UTC).isoformat()}")

    from transformers import AutoModelForCausalLM, AutoTokenizer

    # Determine device
    if torch.backends.mps.is_available():
        device = "mps"
    elif torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"

    train_path = "data/compile-train.jsonl"
    eval_path = "data/compile-eval.jsonl"
    test_path = "data/compile-test.jsonl"

    # Count training examples
    with open(train_path) as f:
        n_train = sum(1 for line in f if json.loads(line)["output"])

    print(f"  Student: {STUDENT_MODEL}")
    print(f"  Device: {device}")
    print(f"  Training data: {train_path} ({n_train} examples)")
    print(f"  Eval data: {eval_path}")

    # Load student
    banner("LOADING STUDENT")
    tokenizer = AutoTokenizer.from_pretrained(STUDENT_MODEL)
    model = AutoModelForCausalLM.from_pretrained(
        STUDENT_MODEL,
        torch_dtype=torch.float32,  # fp32 for stability on MPS
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters: {n_params:,}")
    print(f"  Layers: {model.config.num_hidden_layers}")
    print(f"  Heads: {model.config.num_attention_heads}")
    print(f"  Hidden: {model.config.hidden_size}")
    print(f"  EOS token: {tokenizer.eos_token!r} (id={tokenizer.eos_token_id})")

    # Baseline: can the student compile BEFORE training?
    eval_results_baseline, baseline_rate = evaluate_student(
        model, tokenizer, eval_path, device, label="BASELINE (before training)"
    )

    # Train
    epoch_losses = train_student(model, tokenizer, train_path, device)

    # Evaluate after training — main eval set
    eval_results, final_rate = evaluate_student(
        model, tokenizer, eval_path, device, label="EVAL (after training)"
    )

    # Evaluate on holdout predicates (novel predicate test)
    test_results = None
    test_rate = None
    if Path(test_path).exists() and Path(test_path).stat().st_size > 0:
        test_results_list, test_rate = evaluate_student(
            model, tokenizer, test_path, device,
            label="HOLDOUT (novel predicates)",
        )
        test_results = test_results_list

    # Save model
    model.save_pretrained(MODEL_DIR)
    tokenizer.save_pretrained(MODEL_DIR)
    print(f"\n  Model saved to {MODEL_DIR}")

    # Summary
    elapsed = time.time() - start
    banner(f"SUMMARY — {elapsed:.0f}s")
    print(f"  Student: {STUDENT_MODEL} ({n_params:,} params)")
    print(f"  Training examples: {n_train}")
    print(f"  Baseline P(lambda): {baseline_rate:.0%}")
    print(f"  Final P(lambda): {final_rate:.0%}")
    if test_rate is not None:
        print(f"  Holdout P(lambda): {test_rate:.0%}")
    print(f"  Loss curve: {[f'{l:.3f}' for l in epoch_losses]}")

    # Aggregate structural metrics
    n_parse = sum(1 for r in eval_results if r["metrics"]["parses"])
    n_rep = sum(1 for r in eval_results if r["metrics"]["has_repetition"])
    n_exact = sum(1 for r in eval_results if r["metrics"]["exact_match"])
    n = len(eval_results)
    print(f"  Grammar parse: {n_parse}/{n} ({n_parse/n:.0%})")
    print(f"  Repetition: {n_rep}/{n} ({n_rep/n:.0%})")
    print(f"  Exact match: {n_exact}/{n} ({n_exact/n:.0%})")

    save_json(RESULTS_DIR / "summary.json", {
        "timestamp": datetime.now(UTC).isoformat(),
        "version": 2,
        "elapsed_s": elapsed,
        "student_model": STUDENT_MODEL,
        "n_params": n_params,
        "n_train": n_train,
        "n_eval": len(eval_results),
        "baseline_p_lambda": baseline_rate,
        "final_p_lambda": final_rate,
        "holdout_p_lambda": test_rate,
        "epoch_losses": epoch_losses,
        "eval_results": eval_results,
        "holdout_results": test_results,
        "changes": [
            "EOS token in training targets (fixes repetition)",
            "GBNF grammar-constrained teacher (Montague-style)",
            "Structural eval metrics",
            "Novel predicate holdout test",
        ],
    })


if __name__ == "__main__":
    main()
